/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeCoverage;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testAdd() {
        App classUnderTest = new App();
        assertEquals(3, classUnderTest.add(1, 2));
    }
}
