/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeCoverage;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

    }

    public static int add(int a, int b) {
        return a+b;
    }
}
